services:
  php:
    image: php:8.2-fpm
    env_file: .env
    volumes:
      - ./:/var/www/html:cached
    expose:
      - '9000'

  nginx:
    image: nginx:alpine
    ports:
      - '3000:80'
    volumes:
      - ./public:/var/www/html/public:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
